jobs:
  - name: connection-integrated-schedule
    schedule:
      type: integrated
      integrations:
        - abject_normative
        - prodigy_vaso

steps:
  - name: "Call my stored procedure macro"
    command: "dbt run-operation run_proc" # This is the key pa

